In [1]:
import numpy as np

In [2]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a2=np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
a3=np.arange(10).reshape(2,5)
a3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Scalar Operation

In [9]:
a2+a3

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [6]:
print(a1*2)
print(a2*2)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [11]:
# relational operators
a1>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [12]:
a2==5

array([[False, False, False, False, False],
       [ True, False, False, False, False]])

Array-Function

In [16]:
arr=np.random.random((3,3))
arr=np.round(arr*100)
arr

array([[55., 79., 38.],
       [32.,  4., 62.],
       [68., 34., 49.]])

In [18]:
# max/min/sum/prod
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("Sum:",np.sum(arr))
print("Prod:",np.prod(arr))

Max: 79.0
Min: 4.0
Sum: 421.0
Prod: 148442734612480.0


In [20]:
# we also find row-wise and column-wise min max sum etc.
print("Row-wise sum:",np.sum(arr,axis=1))
print("Column-wise sum:",np.sum(arr,axis=0))
print("Row-wise max:",np.max(arr,axis=1))
print("Column-wise max:",np.max(arr,axis=0))

Row-wise sum: [172.  98. 151.]
Column-wise sum: [155. 117. 149.]
Row-wise max: [79. 62. 68.]
Column-wise max: [68. 79. 62.]


In [23]:
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))

46.77777777777778
21.295684371240718
49.0


In [24]:
# dot product
a4=np.array([[1,2,3],[4,5,6]])
a5=np.array([[7,8],[9,10],[11,12]])
np.dot(a4,a5)

array([[ 58,  64],
       [139, 154]])