In [ ]:
# 
# %pip install pandas


In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1, 2, 3, 4, 5])

In [ ]:
arr1.ndim

1

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)
print(arr2.shape)

2
(2, 3)


In [ ]:
# np.array([[n], [n], ...])  # shape (m, 1)  --> column vector

In [ ]:
arr3=np.array([[20,30,40,50,90,1000],[60,70,80,90,110,1200],[130,140,150,160,170,1800],[190,200,210,220,230,2400]])
print(arr3.ndim)
print(arr3.shape)   

2
(4, 6)


In [ ]:
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# 3d array
arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr4.ndim)
print(arr4.shape)
print(arr4)


3
(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr5=np.array([[[1,2,],[3,4]],[[5,6],[7,8]]])
print(arr5.ndim)
print(arr5.shape)
arr5

3
(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr6=np.array([[[1,2,3,5],[10,20,30,50],[90,80,70,40]],[[4,5,6,7],[60,70,80,90],[100,110,120,130]],[[11,12,13,14],[21,22,23,24],[31,32,33,34]]])
print(arr6.ndim)
print(arr6.shape)
arr6

3
(3, 3, 4)


array([[[  1,   2,   3,   5],
        [ 10,  20,  30,  50],
        [ 90,  80,  70,  40]],

       [[  4,   5,   6,   7],
        [ 60,  70,  80,  90],
        [100, 110, 120, 130]],

       [[ 11,  12,  13,  14],
        [ 21,  22,  23,  24],
        [ 31,  32,  33,  34]]])

In [ ]:
arr10=np.array([[[0.9,0,6,6.8,0.1]],[[0.7,0.8,0.3,0.2,0.4]],[[0.5,0.9,0.11,0.15,0.99]],[[0.12,0.22,0.32,0.42,0.52]],[[0.62,0.72,0.82,0.92,0.102]],[[0.111,0.222,0.333,0.444,0.555]],[[0.666,0.777,0.888,0.999,0.000]],[[0.123,0.234,0.345,0.456,0.567]],[[0.678,0.789,0.890,0.901,0.012]],[[0.121,0.131,0.141,0.151,0.161]]])
print(arr10.ndim)
print(arr10.shape)
arr10

3
(10, 1, 5)


array([[[0.9  , 0.   , 6.   , 6.8  , 0.1  ]],

       [[0.7  , 0.8  , 0.3  , 0.2  , 0.4  ]],

       [[0.5  , 0.9  , 0.11 , 0.15 , 0.99 ]],

       [[0.12 , 0.22 , 0.32 , 0.42 , 0.52 ]],

       [[0.62 , 0.72 , 0.82 , 0.92 , 0.102]],

       [[0.111, 0.222, 0.333, 0.444, 0.555]],

       [[0.666, 0.777, 0.888, 0.999, 0.   ]],

       [[0.123, 0.234, 0.345, 0.456, 0.567]],

       [[0.678, 0.789, 0.89 , 0.901, 0.012]],

       [[0.121, 0.131, 0.141, 0.151, 0.161]]])

In [ ]:
# vocab_size=20
# man->512-dim=5
# queen
#---
#20
#20,1,512
#3d ko ham tensor bolte hain

In [ ]:

np.array([1, 2, 3])
np.zeros((3, 4))
np.ones((2, 2))
np.random.rand(3, 3)
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [ ]:
np.ndarray

numpy.ndarray

In [ ]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
arr512=np.arange(0,512).reshape(1,512)

In [ ]:
arr512.ndim

2

In [ ]:
arr512.shape


(1, 512)

In [ ]:
arr3d=arr512.reshape(1,1,512)

In [ ]:
arr3d.shape

(1, 1, 512)

In [ ]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
          60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
          72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
          96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
         108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
         120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
         132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
         144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
         156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
         168, 169, 170, 171, 172, 

In [ ]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

RANDOM value to create array

In [ ]:
randomarr=np.random.rand(10,10)
randomarr

array([[0.08452015, 0.11045634, 0.52997489, 0.21587553, 0.1018172 ,
        0.18311796, 0.06413036, 0.43521987, 0.38941271, 0.21617131],
       [0.99466336, 0.39644094, 0.54166527, 0.22505604, 0.00255004,
        0.27430176, 0.71778522, 0.97442444, 0.68246324, 0.66688579],
       [0.60656213, 0.04542497, 0.81479407, 0.80153129, 0.90654827,
        0.9712269 , 0.6280557 , 0.09091536, 0.34082105, 0.41362753],
       [0.5519688 , 0.13804184, 0.45288586, 0.173442  , 0.48189115,
        0.29838482, 0.93948989, 0.95509557, 0.61541373, 0.30917039],
       [0.80651523, 0.77860626, 0.58031464, 0.53653099, 0.50543384,
        0.16045226, 0.8577901 , 0.00593825, 0.25927397, 0.00981512],
       [0.46547801, 0.57151189, 0.51083571, 0.64904629, 0.80416849,
        0.0768971 , 0.40144388, 0.00448674, 0.32825799, 0.75118328],
       [0.70794946, 0.27257614, 0.45248936, 0.80567962, 0.37978196,
        0.61093913, 0.16904758, 0.46502072, 0.34900713, 0.85242338],
       [0.53110076, 0.62950921, 0.7741187

In [ ]:
arr23=np.random.random((2,3))
print(arr23)
print(arr23.shape)
print(arr23.ndim)

[[0.99804289 0.81834009 0.54650217]
 [0.10560833 0.36323873 0.10033966]]
(2, 3)
2


In [ ]:
# 3D array creation
arr3d=np.random.random((2,3,4))
print(arr3d)
print(arr3d.shape)
print(arr3d.ndim)


[[[3.47700810e-02 2.44422625e-01 6.10913513e-01 5.09694043e-01]
  [5.49692258e-01 1.29607481e-01 2.89317493e-01 7.43045193e-01]
  [2.44804553e-01 1.77093439e-01 1.62793108e-01 8.80990276e-01]]

 [[6.68388125e-01 9.57376251e-01 6.92418168e-01 9.08538912e-01]
  [6.68645828e-01 1.53252704e-01 9.29653591e-01 5.84260255e-01]
  [1.88272661e-04 4.01568296e-02 1.70466221e-01 5.76866877e-01]]]
(2, 3, 4)
3


In [ ]:
# linear space 

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(-9,1,100)

array([-9.        , -8.8989899 , -8.7979798 , -8.6969697 , -8.5959596 ,
       -8.49494949, -8.39393939, -8.29292929, -8.19191919, -8.09090909,
       -7.98989899, -7.88888889, -7.78787879, -7.68686869, -7.58585859,
       -7.48484848, -7.38383838, -7.28282828, -7.18181818, -7.08080808,
       -6.97979798, -6.87878788, -6.77777778, -6.67676768, -6.57575758,
       -6.47474747, -6.37373737, -6.27272727, -6.17171717, -6.07070707,
       -5.96969697, -5.86868687, -5.76767677, -5.66666667, -5.56565657,
       -5.46464646, -5.36363636, -5.26262626, -5.16161616, -5.06060606,
       -4.95959596, -4.85858586, -4.75757576, -4.65656566, -4.55555556,
       -4.45454545, -4.35353535, -4.25252525, -4.15151515, -4.05050505,
       -3.94949495, -3.84848485, -3.74747475, -3.64646465, -3.54545455,
       -3.44444444, -3.34343434, -3.24242424, -3.14141414, -3.04040404,
       -2.93939394, -2.83838384, -2.73737374, -2.63636364, -2.53535354,
       -2.43434343, -2.33333333, -2.23232323, -2.13131313, -2.03

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])