Numpy Attributes

In [2]:
import numpy as np

In [5]:
a1=np.arange(10)
print(a1)
a2=np.arange(12,dtype=float).reshape(3,4)
print(a2)
a3=np.arange(8).reshape(2,2,2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [7]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a1.shape)
print(a2.shape)
print(a3.shape)

1
2
3
(10,)
(3, 4)
(2, 2, 2)


In [9]:
a1.itemsize

8

In [10]:
a2.itemsize

8

In [13]:
b1=np.arange(10,dtype=np.int32)
print(b1)
b1.itemsize

[0 1 2 3 4 5 6 7 8 9]


4

Changing Data type of array 

In [14]:
a3.astype(np.float64)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])