In [1]:
# 
# %pip install pandas


In [2]:
import numpy as np

In [3]:
arr1=np.array([1, 2, 3, 4, 5])

In [4]:
arr1.ndim

1

In [13]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)
print(arr2.shape)

2
(2, 3)


In [16]:
# np.array([[n], [n], ...])  # shape (m, 1)  --> column vector

In [15]:
arr3=np.array([[20,30,40,50,90,1000],[60,70,80,90,110,1200],[130,140,150,160,170,1800],[190,200,210,220,230,2400]])
print(arr3.ndim)
print(arr3.shape)   

2
(4, 6)


In [10]:
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [21]:
# 3d array
arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr4.ndim)
print(arr4.shape)
print(arr4)


3
(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [23]:
arr5=np.array([[[1,2,],[3,4]],[[5,6],[7,8]]])
print(arr5.ndim)
print(arr5.shape)
arr5

3
(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
arr6=np.array([[[1,2,3,5],[10,20,30,50],[90,80,70,40]],[[4,5,6,7],[60,70,80,90],[100,110,120,130]],[[11,12,13,14],[21,22,23,24],[31,32,33,34]]])
print(arr6.ndim)
print(arr6.shape)
arr6

3
(3, 3, 4)


array([[[  1,   2,   3,   5],
        [ 10,  20,  30,  50],
        [ 90,  80,  70,  40]],

       [[  4,   5,   6,   7],
        [ 60,  70,  80,  90],
        [100, 110, 120, 130]],

       [[ 11,  12,  13,  14],
        [ 21,  22,  23,  24],
        [ 31,  32,  33,  34]]])

In [59]:
arr10=np.array([[[0.9,0,6,6.8,0.1]],[[0.7,0.8,0.3,0.2,0.4]],[[0.5,0.9,0.11,0.15,0.99]],[[0.12,0.22,0.32,0.42,0.52]],[[0.62,0.72,0.82,0.92,0.102]],[[0.111,0.222,0.333,0.444,0.555]],[[0.666,0.777,0.888,0.999,0.000]],[[0.123,0.234,0.345,0.456,0.567]],[[0.678,0.789,0.890,0.901,0.012]],[[0.121,0.131,0.141,0.151,0.161]]])
print(arr10.ndim)
print(arr10.shape)
arr10

3
(10, 1, 5)


array([[[0.9  , 0.   , 6.   , 6.8  , 0.1  ]],

       [[0.7  , 0.8  , 0.3  , 0.2  , 0.4  ]],

       [[0.5  , 0.9  , 0.11 , 0.15 , 0.99 ]],

       [[0.12 , 0.22 , 0.32 , 0.42 , 0.52 ]],

       [[0.62 , 0.72 , 0.82 , 0.92 , 0.102]],

       [[0.111, 0.222, 0.333, 0.444, 0.555]],

       [[0.666, 0.777, 0.888, 0.999, 0.   ]],

       [[0.123, 0.234, 0.345, 0.456, 0.567]],

       [[0.678, 0.789, 0.89 , 0.901, 0.012]],

       [[0.121, 0.131, 0.141, 0.151, 0.161]]])

In [28]:
# vocab_size=20
# man->512-dim=5
# queen
#---
#20
#20,1,512
#3d ko ham tensor bolte hain

In [5]:

np.array([1, 2, 3])
np.zeros((3, 4))
np.ones((2, 2))
np.random.rand(3, 3)
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [6]:
np.ndarray

numpy.ndarray

In [46]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
arr512=np.arange(0,512).reshape(1,512)

In [50]:
arr512.ndim

2

In [55]:
arr512.shape


(1, 512)

In [56]:
arr3d=arr512.reshape(1,1,512)

In [57]:
arr3d.shape

(1, 1, 512)

In [58]:
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
          60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
          72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
          96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
         108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
         120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
         132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
         144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
         156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
         168, 169, 170, 171, 172, 

In [45]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])