In [1]:
import numpy as np

In [2]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2=np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a3=np.arange(10).reshape(2,5)
a3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Scalar Operation

In [5]:
a2+a3

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [6]:
print(a1*2)
print(a2*2)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [7]:
# relational operators
a1>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [8]:
a2==5

array([[False, False, False, False, False],
       [ True, False, False, False, False]])

Array-Function

In [9]:
arr=np.random.random((3,3))
arr=np.round(arr*100)
arr

array([[31., 15.,  9.],
       [21., 74., 24.],
       [87., 59., 64.]])

In [10]:
# max/min/sum/prod
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("Sum:",np.sum(arr))
print("Prod:",np.prod(arr))

Max: 87.0
Min: 9.0
Sum: 384.0
Prod: 51275388165120.0


In [11]:
# we also find row-wise and column-wise min max sum etc.
print("Row-wise sum:",np.sum(arr,axis=1))
print("Column-wise sum:",np.sum(arr,axis=0))
print("Row-wise max:",np.max(arr,axis=1))
print("Column-wise max:",np.max(arr,axis=0))

Row-wise sum: [ 55. 119. 210.]
Column-wise sum: [139. 148.  97.]
Row-wise max: [31. 74. 87.]
Column-wise max: [87. 74. 64.]


In [12]:
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))

42.666666666666664
26.919633479426622
31.0


In [13]:
# dot product
a4=np.array([[1,2,3],[4,5,6]])
a5=np.array([[7,8],[9,10],[11,12]])
np.dot(a4,a5)

array([[ 58,  64],
       [139, 154]])

INDEXING AND SLICING

In [14]:
b1=np.random.random((3,3))
print(b1)

[[0.49878591 0.74356377 0.48652227]
 [0.72511045 0.4331451  0.68184019]
 [0.37426775 0.40776469 0.42544021]]


In [15]:
b1=np.random.random(10)
b2=np.arange(12).reshape(3,4)
b3=np.arange(8).reshape(2,2,2)
print(b1)
print(b2)
print(b3)

[0.32243861 0.253596   0.94127007 0.65702852 0.28978301 0.64916022
 0.14059421 0.7938818  0.49255236 0.17039882]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [16]:
print(b1[-1])
print(1)

0.17039882234616888
1


In [17]:
b2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
print(b2[1,2])
print(b2[2,2])

6
10


In [19]:
print(b3)
print(b3[1,0,1])
print(b3[0,1,0])
print(b3[1,1,1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
2
7


In [20]:
for i in np.nditer(b3):
    print(i)

0
1
2
3
4
5
6
7


In [21]:
b1[2:6]

array([0.94127007, 0.65702852, 0.28978301, 0.64916022])