In [1]:
import numpy as np

In [2]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2=np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a3=np.arange(10).reshape(2,5)
a3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Scalar Operation

In [5]:
a2+a3

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [6]:
print(a1*2)
print(a2*2)

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [7]:
# relational operators
a1>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [8]:
a2==5

array([[False, False, False, False, False],
       [ True, False, False, False, False]])

Array-Function

In [9]:
arr=np.random.random((3,3))
arr=np.round(arr*100)
arr

array([[20., 26., 27.],
       [63., 62., 68.],
       [93., 97., 53.]])

In [10]:
# max/min/sum/prod
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("Sum:",np.sum(arr))
print("Prod:",np.prod(arr))

Max: 97.0
Min: 20.0
Sum: 509.0
Prod: 1782948553364160.0


In [11]:
# we also find row-wise and column-wise min max sum etc.
print("Row-wise sum:",np.sum(arr,axis=1))
print("Column-wise sum:",np.sum(arr,axis=0))
print("Row-wise max:",np.max(arr,axis=1))
print("Column-wise max:",np.max(arr,axis=0))

Row-wise sum: [ 73. 193. 243.]
Column-wise sum: [176. 185. 148.]
Row-wise max: [27. 68. 97.]
Column-wise max: [93. 97. 68.]


In [12]:
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))

56.55555555555556
26.50413431528125
62.0


In [13]:
# dot product
a4=np.array([[1,2,3],[4,5,6]])
a5=np.array([[7,8],[9,10],[11,12]])
np.dot(a4,a5)

array([[ 58,  64],
       [139, 154]])

INDEXING AND SLICING

In [18]:
b1=np.random.random((3,3))
print(b1)

[[0.8944476  0.41138387 0.85228135]
 [0.4064012  0.17865605 0.92945845]
 [0.18490579 0.92767052 0.59580246]]


In [21]:
b1=np.random.random(10)
b2=np.arange(12).reshape(3,4)
b3=np.arange(8).reshape(2,2,2)
print(b1)
print(b2)
print(b3)

[0.25560335 0.27245666 0.66046329 0.53057419 0.90190446 0.64665335
 0.29403251 0.58648601 0.56866564 0.69839723]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
print(b1[-1])
print(1)

0.6983972261744161
1


In [26]:
b2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
print(b2[1,2])
print(b2[2,2])

6
10


In [33]:
print(b3)
print(b3[1,0,1])
print(b3[0,1,0])
print(b3[1,1,1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
2
7


In [35]:
for i in np.nditer(b3):
    print(i)

0
1
2
3
4
5
6
7


In [34]:
b1[2:6]

array([0.66046329, 0.53057419, 0.90190446, 0.64665335])