### Numpy

##### Practice 01

- Create a $3 \times 3$ matrix with values ranging from 0 to 8. Then, write code to:
    - Extract the specific value 4 (the center element).
    - Extract the sub-array [[0, 1], [3, 4]].

RULE OF Sciling arr[row_start : row_end , col_start : col_end]



In [29]:
import numpy as np

arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
for i in arr:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [30]:
arr[1,1]

np.int64(4)

In [35]:
arr[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [36]:
arr2=np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
print(arr2[0:2,0:2])
print(arr2[1:3,1:3])
print(arr2[2:4,2:4])
print(arr2[1:3,1:3])
print(arr2[2:4,2:4])

[[0 1]
 [5 6]]
[[ 6  7]
 [11 12]]
[[12 13]
 [17 18]]
[[ 6  7]
 [11 12]]
[[12 13]
 [17 18]]


In [55]:
arr2[2:4,3:5] #3-1=2 end index is exclusive

array([[13, 14],
       [18, 19]])

In [ ]:
arr2

array([[12]])

In [56]:
arr3=np.arange(25).reshape(5,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
arr3[2:4,1:3]

array([[11, 12],
       [16, 17]])