2. Element-wise Operations vs. Matrix Multiplication
- Given two random $3 \times 3$ arrays A and B:
- Compute the element-wise product.
- Compute the matrix dot product using np.dot or the @ operator.
- Add a comment explaining the mathematical difference between the two operations.

In [7]:
import numpy as np

A=np.random.random((3,3))
print(A.shape)
B=np.random.random((3,3))
print(B.shape)

(3, 3)
(3, 3)


In [9]:
A

array([[0.75917532, 0.41802295, 0.14826852],
       [0.00368817, 0.95749825, 0.06175394],
       [0.69495875, 0.49108226, 0.58920751]])

In [10]:
B

array([[0.72732885, 0.63859415, 0.56580527],
       [0.94127038, 0.71354263, 0.29509579],
       [0.82392261, 0.401197  , 0.40283771]])

In [8]:
A*B

array([[0.55217011, 0.26694701, 0.08389111],
       [0.00347157, 0.68321582, 0.01822333],
       [0.57259222, 0.19702073, 0.23735501]])

In [12]:
arr=np.dot(A,B)
arr

array([[1.06780452, 0.842567  , 0.61263036],
       [0.95482772, 0.71034656, 0.3095173 ],
       [1.45316613, 1.03059301, 0.77548263]])

In [22]:
a1=np.array([1,2,3,4])
b1=np.array([[2],[2],[2],[2]])

In [23]:
a1@b1

array([20])

In [24]:
np.dot(a1,b1)

array([20])

In [ ]:
a1

In [14]:
arr1=A@B
arr1

array([[1.06780452, 0.842567  , 0.61263036],
       [0.95482772, 0.71034656, 0.3095173 ],
       [1.45316613, 1.03059301, 0.77548263]])

In [25]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [26]:
print(A @ B)
print(np.dot(A,B))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [28]:
A = np.ones((2,3,4))
B = np.ones((2,4,5))
print(A @ B)
print(np.dot(A,B))


[[[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]]
[[[[4. 4. 4. 4. 4.]
   [4. 4. 4. 4. 4.]]

  [[4. 4. 4. 4. 4.]
   [4. 4. 4. 4. 4.]]

  [[4. 4. 4. 4. 4.]
   [4. 4. 4. 4. 4.]]]


 [[[4. 4. 4. 4. 4.]
   [4. 4. 4. 4. 4.]]

  [[4. 4. 4. 4. 4.]
   [4. 4. 4. 4. 4.]]

  [[4. 4. 4. 4. 4.]
   [4. 4. 4. 4. 4.]]]]


In [29]:
# @ is strict matrix multiplication, np.dot() is dimension-dependent and can behave differently for higher-dimensional arrays.